site_name: CTF articles by humbledragon669
site_description: Writups for CTF challenges and security labs
site_author: janekpstudentad

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - search.suggest
  palette:
    primary: purple
    scheme: slate
  logo: assets/user_logo.png
  favicon: assets/user_logo.png

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - attr_list

plugins:
  - tags
  - search

nav:
  - Home: index.md
  - Hackviser:
    - Scenarios and Labs: hackviser/index.md
  - Hack The Box:
    - Coming Soon: hackthebox/index.md
  - TryHackMe:
    - Coming Soon: tryhackme/index.md
  - Tags: tags.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/janekpstudentuad
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jane-kocan-payne-662692166/